[package]
<<<<<<< HEAD
name = "core"
=======
name = "rust_simulation"
>>>>>>> port_go_to_rust
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
<<<<<<< HEAD
name = "core"
path = "src/lib.rs"
=======
name = "rust_simulation"
>>>>>>> port_go_to_rust
crate-type = ["cdylib"]

[dependencies]
numpy = "0.20.0"
<<<<<<< HEAD
pyo3 = { version = "0.20.0", features = ["extension-module"] }
=======
pyo3 = "0.20.0"
chrono = "0.4.34"
>>>>>>> port_go_to_rust
