sunbeam_up_cmd = "docker compose up -d"
sunbeam_down_cmd = "docker compose down"
sunlink_up_cmd = "docker compose up -d"
sunlink_down_cmd = "docker compose down"
telemetry_enable_cmd = "bash -lc 'cd /Users/joshuariefman/Solar/sunlink && source environment/bin/activate && ./link_telemetry.py -r can --debug'"
