plot_timer_interval = 10
sunbeam_api_url = "localhost:8080"
sunbeam_path = "/Users/joshuariefman/Solar/sunbeam"
sunlink_path = "/Users/joshuariefman/Solar/sunlink"
realtime_event = "June_8th_Testing"
realtime_pipeline = "track_test"
