plot_timer_interval = 2
sunbeam_api_url = "localhost:8080"
sunbeam_path = "/Users/joshuariefman/Solar/sunbeam"
sunlink_path = "/Users/joshuariefman/Solar/sunlink"
realtime_event = "FSGP_2024_Day_1"
realtime_pipeline = "soc_stage"
