from simulation.model.environment.solar_calculations.base_solar_calculations import BaseSolarCalculations
from simulation.model.environment.solar_calculations.OpenweatherSolarCalculations import OpenweatherSolarCalculations
from simulation.model.environment.solar_calculations.SolcastSolarCalculations import SolcastSolarCalculations
